# Generated by Django 5.0.2 on 2024-02-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingerdients', models.CharField(max_length=400)),
                ('price', models.FloatField(default=0)),
                ('Vegetarienne', models.BooleanField(default=False)),
            ],
        ),
    ]
