# Generated by Django 5.0.2 on 2024-02-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ingerdients',
            new_name='ingredients',
        ),
    ]
